version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: kkkk
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: task
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432

volumes:
  postgres: